version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "80"
      volumes:
          - ./app:/var/app
      environment:
          - VIRTUAL_HOST=lemp.com
          - VIRTUAL_PORT=80
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=lemp"      
  db:
      image: mariadb
      environment:
          - MYSQL_DATABASE=lemp      
          - MYSQL_ROOT_PASSWORD=changeme

#      volumes:
#          - ./database:/var/lib/mysql
